### ISSUE TITLE
Full screen not working as intended and weird DPI Scaling bug 

### ISSUE THREAD

**Issue by levinaHR** [Ruin0x11/ElonaPlusCustom_GX#21]
I think I found 2 problems for 2.06fix Custom-GX 2.0. The first one is when I set the game to full screen, it'll only remove the menu bar and cover some of my screen unlike in previous version. Now if I set the DPI scaling to 1.4 for 800x600 resolution, it'll go full screen correctly, but for some reason the game will crash with access violation exception if I use custom music. The crash happens ONLY if i set the DPI scaling to other than the default value and use custom music.

**Comment by Ruin0x11** [comment]
This should be fixed in [2.07.1.0](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.07.1.0). Could you take a look and see if it works?

**Comment by levinaHR** [comment]
@Ruin0x11 No, unfortunately not. Full screen still only covered part of my top left screen, unlike in 2.06fix 1.0 where it would go to full screen correctly as if I changed my windows display settings to 800 x 600.
If I change the DPI scaling to 1.5 the game will cover most of my screen, but will cut a portion of the bottom game screen. 

Unfortunately the DPI scaling will give the game error message and can't be played. The error occurs when loading a save or after the intro when you get into the first talk with Lomias. Here's the screenshots:

The red line is where the game screen will be cut if i set the DPI scaling to 1.5
![Screenshot (110)](https://user-images.githubusercontent.com/60391223/138222823-f9670464-ce47-4463-aa3e-84f3f3f1922e.png)
![Screenshot (112)](https://user-images.githubusercontent.com/60391223/138222880-296d13bb-a6cd-4a3c-9a75-b09c9682932d.png)

And here's the error when you get into the gameplay with the same settings.
![Screenshot (109)](https://user-images.githubusercontent.com/60391223/138223049-bc3733c7-98fa-466c-b356-751599471a40.png)

**Comment by Ruin0x11** [comment]
[2.07.1.1](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.07.1.0) should fix some of the DPI/screen resolution errors. Does it work for you?

**Comment by levinaHR** [comment]
I'm sorry, but it's still the same. Full screen is not "true" full screen and DPI scaling still causes the game to crash randomly or when changing map with custom music, but now even with original music I'm getting error pop up whenever the gameplay begins. Let me know if there's anything I can help you debug this.

**Comment by Ruin0x11** [comment]
Perhaps you could share the exact contents of your install folder to see if I can reproduce the issue on my machine?

Also, there are some combinations of screen resolutions and DPI that won't activate "true" fullscreen that covers the entire display like you're mentioning. The final (post-DPI-multiplied) resolution has to be supported by your graphics hardware for fullscreen to work properly, as in it has to be in the list of available resolutions in the options menu. That appears to be a limitation of HSP. But for resolutions like 720p and 1.5 DPI scaling to 1080p, the fullscreen should still work, so long as the resolutions list has 1920x1080 included.

**Comment by levinaHR** [comment]
The game folder is in my C:\User\Name\Downloads\Compressed and I didn't change anything other than adding custom music in user\music folder to try and see if the error still persist. So far all of the crash and error is caused by DPI scaling on my end, whether using custom music or not for version 2.07.1.1

Edit: 
Also 1920x1080 resolution or 720p with 1.5 DPI scaling will cut off a large portion of the bottom and right part of the game screen, the only way I can play it in fullscreen correctly is by manually changing my windows display resolution to 800x600 as for now. It's fine but kinda annoying to change my resolution back and forth.

**Comment by Ruin0x11** [comment]
So I did actually manage to trigger the same error as you when trying to enter the game by setting a combination of screen resolution and DPI that exceeded the maximum resolution my display supported. I think that's what's going on.

800x600 at 1.5 DPI should result in a scaled resolution of 1200x900, but from your screenshots, it *also* appears that you're running Windows with its OS-level HiDPI scaling settings, so the actual internal resolution exceeds 1080p heightwise. That explains the portion cut off at the bottom.

My theory is that your display limits the maximum resolution for graphics applications to 1920x1080. But since the window is taller than that, the game crashes when rendering because it's trying to operate on a graphics buffer greater than 1080 pixels in height.

As for myself, I *don't* run Windows in HiDPI mode, since I still have an older non-HiDPI monitor with 1920x1200 resolution. Therefore, when I scale 720p by 1.5, I can always reasonably expect the final window resolution to be 1080p.

However, with Windows' HiDPI scaling also taking effect, this is evidently not always the case.

So I think the solution is to tell Windows *not* to attempt to perform its system-level HiDPI upscaling on CGX, and instead have the scaling managed entirely by CGX instead.

As for fixing your current issue, please try this and see if it works:

1. Right click the `elonapluscgx.exe` executable and select `Properties...`.
2. Go to the `Compatibility` tab and click `Change high DPI settings`
3. Under the `High DPI scaling override` section, tick the box that says `Override high DPI scaling behavior` and select `Application` from the drop-down menu.

Also, as mentioned before, the final scaled resolution has to be supported by your display to be able to enter fullscreen. For 1.5 scaling, you'd have to select "1280x720" to have true 1080p fullscreen. I agree that this is confusing. I will at least try to make CGX pop up a warning if a resolution that will cause crashing is detected, and try to revert to a sane configuration automatically.

So for the moment, as long as there is no portion of the game window that doesn't fit within the size of display (like in your example), I *think* the crashing shouldn't happen.

**Comment by levinaHR** [comment]
Ooh so that's what's causing the crash.
I've tried setting the High DPI scaling override to application but the game still exceeds 1080p for some reason, whether i use 800x600 or 1280x720 with 1.5 scaling. I've also tried ticking the Program DPI option too.

**Comment by levinaHR** [comment]
So after playing around with the settings, here are my findings:
I run the game with these settings using no custom music first, then doing the same thing with custom music. Some of the settings will crash the game with access violation exception if using custom music (doesn't make any sense to me but it is what it is). Also, I'm only checking until 1280x960 because more than that the game exceeds 1080p by a lot.
1. Any resolution with 1.5 DPI Scaling will cause the game to exceed 1080p, even with High DPI scaling override to application.
2. Without DPI Scaling and High DPI Scaling override:
    - 768p reduce my display res but the game runs very blurry and not in fullscreen.
    - 864p will give me a square game screen that's fit to 1080p, but will produce error pop up and can't be played.
    - 720p same as 768p.
    - 960p will give me a square game screen that exceeds 1080p but will produce error pop up and can't be played.
    - Using custom music, 864p and 960p can get into the gameplay without error pop up, but except for 600p and 720p the game will crash randomly or immediately when changing map.
3. Without DPI Scaling but with High DPI scaling override set to application:
    - 768p can run the game to true fullscreen (square screen with black edges but it's a bit blurry though). 
    - 864p will give me a square game screen that's fit to 1080p and can be played.
![Screenshot (113)](https://user-images.githubusercontent.com/60391223/138541271-c52707f8-2854-462f-a73a-86037d1548de.png)
    - 720p  can run the game to true fullscreen (a bit blurry too).
    - 960p will give me a square game screen that exceeds 1080p, but i can still play and change maps.
![Screenshot (114)](https://user-images.githubusercontent.com/60391223/138541526-617290f2-7e07-4752-8236-12a447ecf905.png)
    - Using custom music, only 960p will crash randomly or immediately when changing map.
4. Using the rest of the resolution will exceeds the game screen by a lot, and some of them will produce error pop up on gameplay.

**Comment by Ruin0x11** [comment]
So I will probably fix this by removing the option for arbitrary DPI scaling, and only allowing combinations of DPI that make sense for the current display. In such a change "1280x720 * 1.5 DPI" would become one of the valid screen resolution options, and you wouldn't have to guess if it's supported or not.

I'm thinking the crashes caused by custom music are something related to memory corruption, because they only come up when changing some unrelated settings. Memory corruption bugs are at times bewildering since there isn't a clear reason why things break. Trying to draw something past the screen boundaries might be crashing when it tries to access memory reserved by the custom music that's playing, or something similar.

As an aside, I find it ridiculous that you can crash the HSP runtime this easily just by giving it some invalid parameters. It's just so *weird* that as an end-user you have to make sure the resolution is a multiple of 4, for example...

**Comment by levinaHR** [comment]
Yeah the custom music thing is really weird. While it will crash the game, it can also make some of the settings with error pop up on gameplay like 864p and 960p be played (though it will crash at some point).

**Comment by blazer30** [comment]
I was notified about this thread so I'll post it here.

I earlier used Windowed Mode since I prefer it and went through the Full Screen options. It still crashes and it looks like the moon image is a bit cut off at my current monitor resolution of 2560x1440. It crashes at resolutions above 1600x900 and it stops being full screen at lowered resolutions.

**Comment by levinaHR** [comment]
So I finally found the problem, it was the windows display settings that can break the game. My Scale and Layout is set to the recommended setting which is 125%, and it screwed the game's display and DPI scaling. I never thought to change it before because the previous version (2.06fix 1.0) ignores this setting and acted like the Scale and Layout is 100%.

**Comment by Ruin0x11** [comment]
In 2.07.2.0, the game will ignore the system-level DPI scaling and only use the DPI scaling configured in-game. I also fixed a few other potential crashes related to system scaling that I wasn't previously aware of. If crashes related to scaling still happen then please let me know.
